name: 🛠️  DevExp Issue
description: Add a new issue to the Developer Experience Working Group board.
body:
  - type: markdown
    attributes:
      value: |
        Refer to [OEP-21](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0021-proc-deprecation.html) for more detail on the deprecation and removal process. This ticket should only be used for proposing the removal of an Open edX technology.
        Please leave [DEPR] in the title of your ticket!
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Provide a summary necesary to understand the issue plus relevant links, screenshots, logs, other issues, etc.
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Provide a checklist of steps required to resolve the issue.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: (Optional) Include any open questions, notes from previous implementations, etc.
