name: 🛠️  DevExp Issue
description: Create a new issue for the Developer Experience Working Group.
assignees:
  - kdmccormick
body:
  - type: markdown
    attributes:
      value: |
          Thanks for your submission! This will be temporarily assigned to @kdmccormick so that he'll remember to add it to the [Developer Experience WG project board](https://github.com/orgs/openedx/projects/37).
  - type: textarea
    id: background
    attributes:
      label: Background
      description: Provide a summary to help others to understand the issue, plus any relevant links, screenshots, logs, other issues, etc.
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Provide a checklist of steps required to resolve the issue. If you're not sure, you can provide an incomplete list, or just write "TBD".
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: (Optional) Include any open questions, notes from previous implementations, etc.
